In [ ]:
#ANS=1a
import numpy as  np
temps = np.array([25.3, 26.1, 27.8, 29.0, 28.4, 30.2])
np.average(temps)

np.max(temps)
#np.min(temps)

np.float64(30.2)

In [ ]:
#b
import numpy as  np
temps = np.array([25.3, 26.1, 27.8, 29.0, 28.4, 30.2])
np.max(temps)
#30.2
np.min(temps)

np.float64(30.2)

In [3]:
#c
import numpy as  np
temps = np.array([25.3, 26.1, 27.8, 29.0, 28.4, 30.2])
new_temps=(temps)+2
print(new_temps)


[27.3 28.1 29.8 31.  30.4 32.2]


In [41]:
#ans=2
prices = np.array([101, 103, 98, 97, 105, 110, 115]) 
prices[1:]


array([103,  98,  97, 105, 110, 115])

In [66]:
prices = np.array([101, 103, 98, 97, 105, 110, 115]) 
print(len(prices[prices>100]))

5


In [71]:
prices = np.array([101, 103, 98, 97, 105, 110, 115])
avg=np.average(prices)
print(prices[prices>avg])

[105 110 115]


In [ ]:
image = np.array([[120, 200, 30], 
                  [255, 100, 75], 
                  [0, 180, 220]]) 
 
