In [9]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [11]:
arr1 = np.array([2,3,4,5])
print(arr1)

[2 3 4 5]


In [5]:
arr1=np.zeros([2,3,5,6])

print(arr1)
print("Shape:", arr1.shape)

[[[[0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0. 0.]]]]
Shape: (2, 3, 5, 6)


In [15]:
arr2=np.zeros((2,3))
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]]


In [22]:
arr3=np.arange(1,50,5)
print(arr3)

[ 1  6 11 16 21 26 31 36 41 46]


In [19]:
arr3=np.ones((5,4))
print(arr3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [25]:
arr2=np.arange(3,31,3)
print(arr2)


[ 3  6  9 12 15 18 21 24 27 30]


In [ ]:
arr1=np.array([2,3,5,7,8])
print(arr1)


[2 3 5 7 8]


In [46]:
arr=np.full((3,3,3,3),5)
print(arr)
print(arr.ndim)
print


[[[[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]]


 [[[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]]


 [[[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]

  [[5 5 5]
   [5 5 5]
   [5 5 5]]]]
4


<function print(*args, sep=' ', end='\n', file=None, flush=False)>

In [8]:
arr=np.array([
    [[2,34,44]],[[45,64,57]],[[75,24,87]]
    ])
  
print(arr)
arr.ndim




[[[ 2 34 44]]

 [[45 64 57]]

 [[75 24 87]]]


3

In [64]:
a=(3,4,8,2,5,1,2,6,96,0)
np.sort(a)


array([ 0,  1,  2,  2,  3,  4,  5,  6,  8, 96])

In [10]:
# a=(23,6,4,32,56,4,39,9)
# b=(2,5,7,3,2,5,125,42,)
# np.concatenate((a,b))


a = np.array([23, 45, 65, 42, 2, 33, 446, 4, 3])
b = np.array([21, 3, 3, 22, 34, 33, 32, 33])

result = np.concatenate((a, b), axis=0)
print(result)


# # a=np.array([[23,45,65],[42,2,33],[8,4,3]])
# # b =np.array([[1,3,3],[7,22,34],[33,32,33]])

# # print(
# #     np.concatenate((a, b)))


[ 23  45  65  42   2  33 446   4   3  21   3   3  22  34  33  32  33]


In [ ]:
import numpy as np
a=np.array([[ 0,  1,   788, 3,  4],
       [ 5,  6,  7,  89,  9],
       [10, 11, 12,78, 14]])
# a.shape
# (3,5)

print(a.shape)

# a.dtype.name
# #'int64'
# a.itemsize
# # "8"
# a.size
# 15
type(a)

(3, 5)


numpy.ndarray

In [45]:
c=np.array([[1,2,3],[11,33,22],[22,11,55]],dtype=complex)
c

array([[ 1.+0.j,  2.+0.j,  3.+0.j],
       [11.+0.j, 33.+0.j, 22.+0.j],
       [22.+0.j, 11.+0.j, 55.+0.j]])

In [13]:
a=np.arange(6)
# print(a)
b=np.arange(12).reshape(4,3)
print(b)
c=np.arange(24).reshape(2,3,4)
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
rg = np.random.default_rng(1)  # create instance of default random number generator
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3
# # print(a)
# b+=a
# b


In [ ]:

random_float = rng.random()
print(f"Single random float: {random_float}")

random_array_floats = rng.random(size=(2, 3))
print(f"Array of random floats:\n{random_array_floats}")

Single random float: 0.39710198910204464
Array of random floats:
[[0.44523642 0.16889619 0.81012038]
 [0.48515682 0.26674954 0.12130618]]


In [123]:
random_int = rng.integers(0, 10)  # Random integer between 0 and 9
print(f"Single random integer: {random_int}")

random_array_ints = rng.integers(1, 100, size=5) # 5 random integers between 1 and 99
print(f"Array of random integers: {random_array_ints}")

normal_sample = rng.normal(loc=10, scale=2, size=5)
print(f"Samples from a normal distribution: {normal_sample}")

arr = np.array([1, 2, 3, 4, 5])
rng.shuffle(arr)
print(f"Shuffled array: {arr}")

permuted_range = rng.permutation(10) # Permutation of numbers from 0 to 9
print(f"Permuted range: {permuted_range}")

rng_seeded = np.random.default_rng(seed=42)
first_run = rng_seeded.random(size=3)

rng_seeded_again = np.random.default_rng(seed=42)
second_run = rng_seeded_again.random(size=3)

print(f"First run with seed 42: {first_run}")
print(f"Second run with seed 42: {second_run}")

import numpy as np

rng_seeded = np.random.default_rng(seed=42)


# Generate a single random float between 0.0 and 1.0
random_float = rng_seeded.random()
print(f"Random float: {random_float}") # Output will be consistently 0.7739560485559633

# Generate an array of 3 random integers between 0 (inclusive) and 10 (exclusive)
random_integers = rng_seeded.integers(low=0, high=10, size=3)
print(f"Random integers: {random_integers}") # Output will be consistently [6 2 7]

# Generate a 3x3 array of random numbers from a normal distribution
random_normal_array = rng_seeded.normal(loc=0.0, scale=1.0, size=(3, 3))
print(f"Random normal array:\n{random_normal_array}")


Single random integer: 8
Array of random integers: [86 72 28 87 91]
Samples from a normal distribution: [12.82126517  9.787883    6.24409218 10.03144114 10.23070268]
Shuffled array: [5 3 2 1 4]
Permuted range: [0 4 6 1 8 5 7 2 3 9]
First run with seed 42: [0.77395605 0.43887844 0.85859792]
Second run with seed 42: [0.77395605 0.43887844 0.85859792]
Random float: 0.7739560485559633
Random integers: [6 4 4]
Random normal array:
[[ 0.94056472 -1.95103519 -1.30217951]
 [ 0.1278404  -0.31624259 -0.01680116]
 [-0.85304393  0.87939797  0.77779194]]


In [15]:
import numpy as np
rng = np.random.default_rng()  # create a random generator (without seed)
random_int = rng.integers(0, 10,8)
rng1 = np.random.default_rng(seed=23)
rng2 = np.random.default_rng(seed=23)
print(random_int)

print(rng1.integers(0, 10, 5))
print(rng2.integers(0, 10, 5))

[1 5 9 2 6 1 5 7]
[0 6 4 6 2]
[0 6 4 6 2]


In [ ]:

arr=np.full(10,5)
print(arr)


In [ ]:
#create a arrray of 10 ement which has each element 5
import numpy as np


arr=np.arange(1,11)
print(arr)
arr1=arr.reshape(2,5)
print(arr1)
np.sum(arr1,axis=0)
arr1.(1,10)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [109]:
arr=np.arange(21,31)
a=arr.reshape(2,5)
print(a)

# np.ravel(a)
print(a.flatten)

[[21 22 23 24 25]
 [26 27 28 29 30]]
<built-in method flatten of numpy.ndarray object at 0x000001D96EA0B450>
